language: node_js
node_js:
  - 'node'
env:
  - EXTENSION_ID=nihdgihdhlgebmajigjfnplehjnhlebe
before_install:
  - cd extension
deploy:
  provider: script
  script: npm run version-from-git-tag; npm run release
  on:
    branch: master
    tags: true
